"""Format LLM review responses for GitHub."""

from src.services.github.models import Review, ReviewComment
from src.services.llm.base import InlineComment, ReviewResponse


def format_comment_body(comment: InlineComment) -> str:
    """Format a single comment with category and severity badges."""
    severity_emoji = {
        "CRITICAL": "🔴",
        "WARNING": "🟡",
        "INFO": "🔵",
    }

    category_label = {
        "BUG": "Bug",
        "SECURITY": "Security",
        "PERFORMANCE": "Performance",
        "STYLE": "Style",
        "SUGGESTION": "Suggestion",
        "DOCUMENTATION": "Documentation",
    }

    emoji = severity_emoji.get(comment.severity.value, "🔵")
    category = category_label.get(comment.category.value, "Comment")

    return f"{emoji} **{category}**: {comment.body}"


def format_summary(response: ReviewResponse, files_reviewed: int) -> str:
    """Format the review summary comment."""
    verdict_emoji = {
        "approve": "✅",
        "request_changes": "🔴",
        "comment": "💬",
    }

    verdict_text = {
        "approve": "Approved",
        "request_changes": "Changes Requested",
        "comment": "Review Complete",
    }

    emoji = verdict_emoji.get(response.verdict, "💬")
    verdict = verdict_text.get(response.verdict, "Review Complete")

    lines = [
        f"## {emoji} {verdict}",
        "",
        response.summary,
        "",
        "---",
        f"📊 **Stats**: {files_reviewed} file(s) reviewed | {len(response.comments)} comment(s)",
        f"🤖 **Model**: `{response.model}` | Cost: ${response.cost_usd:.4f}",
        "",
        "<sub>Generated by [CodeRev](https://github.com/yourusername/coderev)</sub>",
    ]

    return "\n".join(lines)


def llm_response_to_github_review(
    response: ReviewResponse,
    files_reviewed: int,
) -> Review:
    """Convert LLM response to GitHub review format."""
    # Map verdict
    event_map = {
        "approve": "APPROVE",
        "request_changes": "REQUEST_CHANGES",
        "comment": "COMMENT",
    }
    event = event_map.get(response.verdict, "COMMENT")

    # Convert inline comments
    github_comments = [
        ReviewComment(
            path=comment.path,
            line=comment.line,
            body=format_comment_body(comment),
            side="RIGHT",
        )
        for comment in response.comments
    ]

    # Build summary
    summary = format_summary(response, files_reviewed)

    return Review(
        body=summary,
        event=event,  # type: ignore[arg-type]
        comments=github_comments,
    )
